import { StyleSheet } from 'react-native'
import Constants from 'expo-constants'

import Colors from '../constants/colors'
import Sizes from '../constants/sizes'

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: Sizes.paddingSize,
    paddingTop: Constants.statusBarHeight + Sizes.paddingSize,
    alignItems: 'center',
  },
  header: {
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.colorArrPreset[5],
    width: '120%',
    paddingBottom: 5,
  },
  titleApp: {
    fontSize: Sizes.fontSize * 1.5,
    color: Colors.colorArrPreset[0],
    fontWeight: 'bold',
  },
  titleText: {
    fontSize: Sizes.fontSize,
    color: Colors.colorArrPreset[1],
  },
  cardList: {
    flexDirection: 'row',
    height: '70%',
  },
  leftList: {
    width: '65%',
  },
  rightList: {
    width: '35%',
    alignItems: 'flex-end',
  },
  simpleText: {
    fontSize: Sizes.fontSize * 1.1,
    color: Colors.colorArrPreset[0],
  },
  botButtons: {
    backgroundColor: Colors.colorArrPreset[4] + '99',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: Sizes.buttonSize,
    borderRadius: Sizes.buttonSize / 2,
    width: Sizes.buttonSize * 4,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 6,
  },
  inputText: {
    borderBottomColor: Colors.colorArrPreset[0],
    borderBottomWidth: 1,
    borderTopColor: Colors.colorArrPreset[0],
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderLeftColor: Colors.colorArrPreset[0],
    borderTopLeftRadius: Sizes.fontSize,
    borderBottomLeftRadius: Sizes.fontSize,
    marginStart: Sizes.fontSize,
    // width: '37%',
    height: Sizes.fontSize * 2,
    textAlign: 'justify',
    textAlignVertical: 'center',
    paddingLeft: Sizes.fontSize / 2.2,
    color: Colors.colorArrPreset[0],
    fontSize: Sizes.fontSize * 1.1,
  },
  input: {
    borderBottomColor: Colors.colorArrPreset[0],
    borderBottomWidth: 1,
    borderTopColor: Colors.colorArrPreset[0],
    borderTopWidth: 1,
    height: Sizes.fontSize * 2,
    width: '30%',
    textAlign: 'center',
    color: Colors.colorArrPreset[0],
    fontSize: Sizes.fontSize * 1.1,
    marginEnd: -5,
  },
  addButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: Sizes.buttonSize,
    height: Sizes.buttonSize,
    borderColor: Colors.colorArrPreset[0],
    borderWidth: Sizes.buttonSize / 50,
    backgroundColor: Colors.colorArrPreset[4],
    borderRadius: Sizes.buttonSize / 2,
  },
  settingsButtons: {
    justifyContent: 'center',
    alignItems: 'center',
    width: Sizes.buttonSize / 1.6,
    height: Sizes.buttonSize / 1.6,
    backgroundColor: Colors.colorArrPreset[0],
    borderRadius: Sizes.buttonSize / 2,
    marginVertical: Sizes.buttonSize / 3,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 6,
  },
  botRowButtons: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: '15%',
    width: Sizes.buttonSize * 4,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  settingsList: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    height: '110%',
    width: '110%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.colorArrPreset[5] + 'DD',
    elevation: 20,
  },
  settingsText: {
    fontSize: Sizes.fontSize,
    color: Colors.colorArrPreset[0],
  },
  settingsInput: {
    fontSize: Sizes.fontSize,
    color: Colors.colorArrPreset[0],
  },
})
